plugins {
	id 'java-library'
	id 'maven-publish'
	id 'signing'
}

sourceCompatibility = 1.17
targetCompatibility = 1.17

def baseVersion = '3.9.4'
def baseGroupId = 'io.github.adempiere'

repositories {
    mavenLocal()
    mavenCentral()
}

allprojects {
    tasks.withType(Javadoc) {
    	options.addStringOption('Xdoclint:none', '-quiet')
   	}
}

dependencies {
   api fileTree(
        dir: 'lib',
        include: [
            '*.jar'
        ]
    )

	// Jakarta RESTful Web Services
	implementation "jakarta.ws.rs:jakarta.ws.rs-api:4.0.0"
	// Jersey core client implementation
	implementation 'org.glassfish.jersey.core:jersey-client:4.0.0'
	implementation 'org.glassfish.jersey.inject:jersey-hk2:4.0.0'

	// JSON in Java
	// https://mvnrepository.com/artifact/org.json/json
	implementation"org.json:json:20250517"

    //	ADempiere Core
    implementation "${baseGroupId}:base:${baseVersion}"
	implementation "${baseGroupId}:project:${baseVersion}"
}

sourceSets {
    main {
         java {
            srcDirs = ['src/main/java']
         }
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}


def entityType = 'ECA46'
group = "io.github.adempiere"
version = System.getenv("ADEMPIERE_LIBRARY_VERSION") ?: "local-1.0.0"
def urlRepository = System.getenv("ERP_LIBRARY_REPO")

jar {
	manifest {
		attributes(
			"Implementation-Title": "ADempiere Business Processors",
			"Implementation-Version": version,
			"EntityType": entityType
		)
    }
}

publishing {
    repositories {
		mavenLocal()

        maven {
            url = urlRepository
            credentials {
                username = System.getenv("GITHUB_DEPLOY_USER") ?: System.properties['deploy.user']
                password = System.getenv("GITHUB_DEPLOY_TOKEN") ?: System.properties['deploy.token'] 
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
			groupId = group
			artifactId = 'adempiere-business-processors'
			version = version
           	from components.java
           	pom {
                name = 'ADempiere Business Processors'
                description = 'A project to convert all processors to process and call it from extern services'
                url = 'http://adempiere.io/'
                licenses {
                    license {
                        name = 'GNU General Public License, version 2'
                        url = 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'yamelsenih'
                        name = 'Yamel Senih'
                        email = 'ysenih@erpya.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/adempiere/adempiere-business-processors.git'
                    developerConnection = 'scm:git:ssh://github.com/adempiere/adempiere-business-processors.git'
                    url = 'http://github.com/adempiere/adempiere-business-processors'
                }
            }
		}
	}
}


task cleanBuildPublishLocal(type: GradleBuild) {
	tasks = ['clean', 'build', 'publishToMavenLocal']
}


signing {
	def isReleaseVersion = !version.toString().startsWith("local") && !version.toString().endsWith("-SNAPSHOT")

	sign configurations.archives

	setRequired {
		// signing is required if this is a release version and the artifacts are to be published
		// do not use hasTask() as this require realization of the tasks that maybe are not necessary
		(isReleaseVersion || version.toString().equals("build")) && gradle.taskGraph.allTasks.any {
			it.equals(PublishToMavenRepository)
		}
	}
	def signingKey = findProperty("deploySigningKey")
    def signingPassword = findProperty("deploySigningPassword")
    useInMemoryPgpKeys(signingKey, signingPassword)
    sign publishing.publications.mavenJava
}
